version: '3.3'

services:
  whoami:
    image: "traefik/whoami"      
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
      mode: replicated
      replicas: 3
  
networks:
  traefik_public:
    external: true