version: '3.3'

services:
  whoami:
    image: "traefik/whoami"      
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${INSTANCE1:?error}.rule=Host(`${INSTANCE1:?error}.localhost`)"
        - "traefik.http.routers.${INSTANCE1:?error}.entrypoints=web"
        - "traefik.http.services.${INSTANCE1:?error}.loadbalancer.server.port=80"
      mode: replicated
      replicas: 3
  
networks:
  traefik_public:
    external: true