version: '3.3'

services:
  cats:
    image: "unfor19/docker-cats"      
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${INSTANCE2:?error}.rule=Host(`${INSTANCE2:?error}.localhost`)"
        - "traefik.http.routers.${INSTANCE2:?error}.entrypoints=web"
        - "traefik.http.services.${INSTANCE2:?error}.loadbalancer.server.port=8080"
      mode: replicated
      replicas: 3
  
networks:
  traefik_public:
    external: true